### ISSUE TITLE
Chart rendering performance

### ISSUE THREAD

**Issue by JeongHun-Park** [fusioncharts/angular2-fusioncharts#14]
Hi.

I am making web page that has many charts and I use angular2 and angular2-fusioncharts.

All charts rendering time was very long when web page has many charts to render.

And I found that ngDoCheck() is problem.

I can get better chart rendering performance after deleting ngDoCheck() in fusioncharts.component.ts.

I think cause of the problem is that angular2 app is run on the zone.

And also I can get better performance using this patch.(https://github.com/fusioncharts/angular2-fusioncharts/pull/13)

Thanks.

**Comment by ariyankhan** [comment]
Hello @JeongHun-Park 
the patch [#13](https://github.com/fusioncharts/angular2-fusioncharts/pull/13) is merged.
Thanks for your valuable contribution.
