### ISSUE TITLE
Cannot compile with --prod version 

### ISSUE THREAD

**Issue by ersinunsal** [fusioncharts/angular2-fusioncharts#18]
I use Fusioncharts in Ionic-2 project. When I compile the project using --prod version, I have the following error.

--  ionic build android --release --prod
-- Error : 

[12:00:15]  Error: ./~/angular2-fusioncharts/index.ts Module build failed: TypeE
rror: Cannot read property 'content' of
            undefined at Object.optimizationLoader
            (D:\FibaRatification\node_modules\@ionic\app-scripts\dist\webpack\op
timization-loader-impl.js:14:24) at ...

**Comment by ariyankhan** [comment]
@ersinunsal 
Try to use the latest version [1.0.3](https://github.com/fusioncharts/angular2-fusioncharts/releases/tag/1.0.3) of angular2-fusioncharts and let me know if you face any problem.
