### ISSUE TITLE
fusion time series chart not working in Safari when using routing.

### ISSUE THREAD

**Issue by surbhi-fotedar** [fusioncharts/angular2-fusioncharts#76]
Angular 8,
Fuison Chart: 3.15.0-sr.1
UI is breaking
![Screenshot 2019-12-23 at 3 21 41 PM](https://user-images.githubusercontent.com/41435418/71352363-21c66f00-259c-11ea-93f5-1bdc62c90698.png)

**Comment by surbhi-fotedar** [comment]
Please find the code base for the given issue: 

https://bitbucket.org/surbhifotedar/fusion-chart-demo/src/master/fusion-chart-demo/

Safari version: 12

**Comment by navdeepothee** [comment]
Hi Surbhi,

Thanks for getting in touch.

This is a bug and we have logged a issue for this internally.

Our engineering team will work on this issue and we will keep you posted on same.

Meanwhile please feel free to revert us back for any further assistance.

Hope this helps.

**Comment by priyanjitdey94** [comment]
@surbhi-fotedar In `app.module.ts`, please add the following line of code
`FusionCharts.options['SVGDefinitionURL'] = 'absolute';` before registering the charts and themes modules to FusionCharts constructor.

ie,
```
FusionCharts.options['SVGDefinitionURL'] = 'absolute'; // add this line
FusionChartsModule.fcRoot(FusionCharts, Charts, FusionTheme);
```

[This stackoverflow answer](https://stackoverflow.com/a/38821357/6023144) explains the reason behind this problem. 

SVG `clippath` is used to clip the canvas area of the chart and prevent any overflow of plots outside the canvas. Though the stackoverflow answer is in context of gradient fill, the problem exists for SVG `clippath` as well.
