### ISSUE TITLE
Cannot assign to read only property '6' of string XX

### ISSUE THREAD

**Issue by GuysmoB** [fusioncharts/angular2-fusioncharts#90]
Hi,

I use FusionChart with Angular 10 for candlestick chart. I have a CSV file where each data (high, open, close ...) are extracted.
I have an error in createDataTable() : 
ERROR Error: Uncaught (in promise): TypeError: Cannot assign to read only property '6' of string '2007-01-02'
TypeError: Cannot assign to read only property '6' of string '2007-01-02'

I started with the example given in a tutorial but I struggle to pass data in a correct format I guess.
At start, data are fetch from a server. See the tutorial : https://www.fusioncharts.com/fusiontime/examples/interactive-candlestick-chart?framework=angular4

[app.component - Copie.txt](https://github.com/fusioncharts/angular-fusioncharts/files/5341497/app.component.-.Copie.txt)
Any idea ?
Thank you :)

**Comment by AyanBhadury** [comment]
Hi,

Here is a working demo fetching data from an external CSV file - https://codesandbox.io/s/csv-angular-demo-wid6v

Hope this helps.

**Comment by GuysmoB** [comment]
Thank you @AyanBhadury, I'll check it !

**Comment by GuysmoB** [comment]
I got it to work on my project ! It seems the .map() method did the trick but I don't understand why.
Can you explain me please @AyanBhadury ?

Thank again :)

**Comment by AyanBhadury** [comment]
@GuysmoB for array.mapmethod refer to this page  : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map
